import random
import string
#create a dictionary with a random number of keys (from 1 to 10) where each key is a random letter and each value is a random number between 0 and 100
def generate_random_dict():
    num_keys = random.randint(1, 10)
    random_dict = {}
    for _ in range(num_keys):
        key = random.choice(string.ascii_lowercase)
        value = random.randint(0, 100)
        random_dict[key] = value
    return random_dict
#create a list containing a random number of dictionaries (from 2 to 10), each of which is generated by the generate_random_dict function
def generate_list_of_dicts():
    num_dicts = random.randint(2, 10)
    list_of_dicts = [generate_random_dict() for _ in range(num_dicts)]
    return list_of_dicts

# result
print(generate_list_of_dicts())